### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/borsh#1]
We can use struct from https://github.com/koute/serde-bench/blob/master/src/lib.rs
and  https://github.com/erickt/rust-serialization-benchmarks/tree/master/rust (cc @frol ) to compare with existing setups.

We can later add benchmarking of BORsh to repos there, but first let's add benchmarking suit here, including some large data structs (e.g. repeated of repeated of repeated fields) to monitor speed.

**Comment by nearmax** [comment]
Closing, since we now have borsh, bincode, cbor, and speedy benchmarks. We can add more benchmarks later.
